### ISSUE TITLE
Help me 帮帮我

### ISSUE THREAD

**Issue by 2010HCY** [MaxChang3/hexo-bilibili-card#11]
Hello, nice to meet you, I like this plugin of yours very much, but I have a little problem, can you help `me？I` can't download it directly with the command, so I downloaded it directly on GitHub and added it to the package.json file, but it reported an error, the error content is as follows, how to solve it
你好，很高兴认识你，我很喜欢你的这个插件，但我遇到了一点问题，你能帮帮我吗？我无法直接用命令下载，我便直接在GitHub下载下来，并将其添加到了package.json文件中，但它报错了，报错内容如下，请问要怎么解决啊
```
ERROR Plugin load failed: hexo-bilibili-card
Error: Cannot find module 'node-fetch-native'
Require stack:
- C:\Users\2010HCY\博客\blog\node_modules\hexo-bilibili-card\lib\bili.js
- C:\Users\2010HCY\博客\blog\node_modules\hexo-bilibili-card\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\2010HCY\博客\blog\node_modules\hexo-bilibili-card\lib\bili.js:2:19)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at req (C:\Users\2010HCY\博客\blog\node_modules\hexo\dist\hexo\index.js:247:31)
    at C:\Users\2010HCY\博客\blog\node_modules\hexo-bilibili-card\index.js:5:24
    at C:\Users\2010HCY\博客\blog\node_modules\hexo\dist\hexo\index.js:255:20
    at tryCatcher (C:\Users\2010HCY\博客\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\2010HCY\博客\blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\2010HCY\博客\blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\2010HCY\博客\blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\2010HCY\博客\blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\2010HCY\博客\blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\2010HCY\博客\blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\2010HCY\博客\blog\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Users\2010HCY\博客\blog\node_modules\bluebird\js\release\async.js:15:14)
```

**Comment by maxchang3** [comment]
最好使用包管理器安装，如 `npm i hexo-bilibili-card` 依赖应该会自动安装的。无法使用命令安装请问报错是什么呢？

或你需要手工添加依赖项（不推荐）

```
"lodash.get": "^4.4.2",
"node-fetch-native": "^1.4.0"
```

或者再你之前安装的基础上再运行一次 `npm i`

**Comment by 2010HCY** [comment]
成功了！我包管理器试了7次成功了！

**Comment by 2010HCY** [comment]
你好，我安装了插件后发现我博客的图标无法交互了，我尝试主题文件重置，插件删除，重启电脑，删除博客根目录下的db.json缓存文件，都无法解决问题。我用的是hexo-theme-ayer主题，该不会是我瞎搞整坏了吧？






                       
原始邮件
                       
                     

发件人："Max Chang"< ***@***.*** &gt;;

发件时间：2024/7/29 12:42

收件人："maxchang3/hexo-bilibili-card"< ***@***.*** &gt;;

抄送人："2010HCY"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [maxchang3/hexo-bilibili-card] Help me 帮帮我 (Issue #11)




 
最好使用包管理器安装，如 npm i hexo-bilibili-card 依赖应该会自动安装的。
 
你需要添加依赖项。
 "lodash.get": "^4.4.2", "node-fetch-native": "^1.4.0"  
或者再运行一次 npm i

**Comment by maxchang3** [comment]
`hexo clean` 试试

**Comment by 2010HCY** [comment]
不行，这个一般是什么问题啊我感觉我几乎将里面的文件置了个遍，但就是不行，显示不出来无法交互，也没有报错







                       
原始邮件
                       
                     

发件人："Max Chang"< ***@***.*** &gt;;

发件时间：2024/7/29 17:33

收件人："maxchang3/hexo-bilibili-card"< ***@***.*** &gt;;

抄送人："2010HCY"< ***@***.*** &gt;;"State change"< ***@***.*** &gt;;

主题：Re: [maxchang3/hexo-bilibili-card] Help me 帮帮我 (Issue #11)




 
hexo clean 试试

**Comment by maxchang3** [comment]
不太好说欸，没遇到过这种情况，hexo-bilibili-card 你卸载的时候其他依赖也去除了吗。只装了我这一个插件吗？ 试试 删除 node_modules 再重新安装呢？

**Comment by 2010HCY** [comment]
hexo-bilibili-card除了他我其他都卸了，因为刚装它时没有问题node_modules这个文件夹我移走试逝







                       
原始邮件
                       
                     

发件人："Max Chang"< ***@***.*** &gt;;

发件时间：2024/7/29 18:46

收件人："maxchang3/hexo-bilibili-card"< ***@***.*** &gt;;

抄送人："2010HCY"< ***@***.*** &gt;;"State change"< ***@***.*** &gt;;

主题：Re: [maxchang3/hexo-bilibili-card] Help me 帮帮我 (Issue #11)




 
不太好说欸，没遇到过这种情况，hexo-bilibili-card 你卸载的时候其他依赖也去除了吗。只装了我这一个插件吗？ 试试 删除 node_modules 再重新安装呢？

**Comment by 2010HCY** [comment]
是博客程序问题，我把主题重装了







                       
原始邮件
                       
                     

发件人："Max Chang"< ***@***.*** &gt;;

发件时间：2024/7/29 18:46

收件人："maxchang3/hexo-bilibili-card"< ***@***.*** &gt;;

抄送人："2010HCY"< ***@***.*** &gt;;"State change"< ***@***.*** &gt;;

主题：Re: [maxchang3/hexo-bilibili-card] Help me 帮帮我 (Issue #11)




 
不太好说欸，没遇到过这种情况，hexo-bilibili-card 你卸载的时候其他依赖也去除了吗。只装了我这一个插件吗？ 试试 删除 node_modules 再重新安装呢？

**Comment by 2010HCY** [comment]
呃，我重装整个博客系统后一切正常，但是装了你的插件，又出现了图标无法显示交互的情况，我把我的博客完整的发给你，一份正常的，一份是安装了插件后的，两者唯一的差别是是否安装哔哩哔哩卡片插件，我不太懂这些






                       
原始邮件
                       
                     

发件人："Max Chang"< ***@***.*** &gt;;

发件时间：2024/7/29 18:46

收件人："maxchang3/hexo-bilibili-card"< ***@***.*** &gt;;

抄送人："2010HCY"< ***@***.*** &gt;;"State change"< ***@***.*** &gt;;

主题：Re: [maxchang3/hexo-bilibili-card] Help me 帮帮我 (Issue #11)




 
不太好说欸，没遇到过这种情况，hexo-bilibili-card 你卸载的时候其他依赖也去除了吗。只装了我这一个插件吗？ 试试 删除 node_modules 再重新安装呢？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;
 


 	
 	 		 			从QQ邮箱发来的超大附件 	
 	 		 				 					 						 							 						 					
 					 						 							安装前blog.7z 							 (36.4MB, 无限期) 						 						 							进入下载页面 							：https://wx.mail.qq.com/ftn/download?func=3&k=9e9c5132ea10c5adacef1e32303566340f70763032356634444c48465656510d505b1d54565157195801000a1f050300544e0106565355035250080a0156763484cdb9da91b083bdec015c5d551b514e75b90aa8589029ecd20b7ae5998e5b84e7bbd73772&key=9e9c5132ea10c5adacef1e32303566340f70763032356634444c48465656510d505b1d54565157195801000a1f050300544e0106565355035250080a0156763484cdb9da91b083bdec015c5d551b514e75b90aa8589029ecd20b7ae5998e5b84e7bbd73772&code=ac0225f4&from= 						
 					
 				
 			
 				 					 						 							 						 					
 					 						 							安装插件后blog.7z 							 (41.7MB, 无限期) 						 						 							进入下载页面 							：https://wx.mail.qq.com/ftn/download?func=3&k=c6995364bd1097abf4ea1a6467353432b210ae66653534321c494c10075605505b5f19070701551f5d5e0c064803030a084b07070453060a5a03070052542232dcc8bd8cc6b0d2bdab828fd280a5ba505509534a524f208b22c227202dccbd7de1171a49a3fcc2b72cc38f&key=c6995364bd1097abf4ea1a6467353432b210ae66653534321c494c10075605505b5f19070701551f5d5e0c064803030a084b07070453060a5a03070052542232dcc8bd8cc6b0d2bdab828fd280a5ba505509534a524f208b22c227202dccbd7de1171a49a3fcc2b72cc38f&code=9f4de542&from=

**Comment by maxchang3** [comment]
安装 `hexo-bilibili-card` 后导致交互出错是 `npm install` 后的副作用.

在这个过程中，（可能由于某些依赖的更新导致）你主题的 jQuery 并没有正确引入。因为许多交互都失效了。

具体来说是你使用主题的 [layout/_partial/after-footer.ejs](https://github.com/shen-yu/hexo-theme-ayer/blob/master/layout/_partial/after-footer.ejs) 中的 js helper 生成的 script 标签都没有在最终产物里。并且经过测试，无论我在 `after_footer.ejs` 中如何添加 `script` 标签（关于 jquery 的）都无法成功。

这个结果不依赖于安装`hexo-bilibili-card`本身，我直接运行 `npm install` 并 `hexo clean` 也会得到相同的结果。

---

进一步分析，似乎 jQuery 之类的依赖被打包成了一个 bundle.js 放到了最下面，但是这样导致了很多 CDN 引入的依赖于 jQuery 代码早于 jQuery 执行了，因此在他们执行的时刻，jQuery 没有被执行，所以报错。

经过排查是依赖 `hexo-filter-optimize` 的问题。该插件会将 hexo 的各个资源（包括 js）进行打包来优化页面加载，但是影响了 jQuery 的加载顺序。

通过检查 `node_modules` 也可以发现，你提供的「安装前 blog」其实也没有安装 `hexo-filter-optimize`。因此，当使用 `npm install` 或安装 `hexo-bilibili-card` 时，他也会一并安装，导致了上诉问题。

以下是一些建议：

设置排除项（排除 jQuery 和 RemixIcon，保证引入顺序）

```yaml
# 在 _config.yml 追加:
filter_optimize:
  enable: true
  # remove the surrounding comments in each of the bundled files
  remove_comments: false
  css:
    # minify all css files
    minify: true
    # bundle loaded css files into one
    bundle: true
    # use a script block to load css elements dynamically
    delivery: true
    # make specific css content inline into the html page
    #   - only support the full path
    #   - default is ['css/main.css']
    inlines:
    excludes:
      - ['/css/fonts/remixicon.css']
  js:
    # minify all js files
    minify: true
    # bundle loaded js files into one
    bundle: true
    excludes:
      - ['/js/jquery-3.6.0.min.js']
```

或修改主题的 js 引入方式，使用 CDN 引入 jQuery 和 RemixIcon。

**Comment by 2010HCY** [comment]
你的意思是我主题没安装好，我再安装其他插件安装依赖后出问题了？我主题是直接打包下载的，因为我用包管理器经常失败







                       
原始邮件
                       
                     

发件人："Max Chang"< ***@***.*** &gt;;

发件时间：2024/7/30 1:34

收件人："maxchang3/hexo-bilibili-card"< ***@***.*** &gt;;

抄送人："2010HCY"< ***@***.*** &gt;;"State change"< ***@***.*** &gt;;

主题：Re: [maxchang3/hexo-bilibili-card] Help me 帮帮我 (Issue #11)




 
安装 hexo-bilibili-card 后导致交互出错是 npm install 后的副作用.
 
在这个过程中，（可能由于某些依赖的更新导致）你主题的 jquery 并没有正确引入。因为许多交互都失效了。
 
具体来说是你使用主题的 layout/_partial/after-footer.ejs 中的 js helper 生成的 script 标签都没有在最终产物里。并且经过测试，无论我在 after_footer.ejs 中如何添加 script 标签（关于 jquery 的）都无法成功。
 
这个结果不依赖于安装hexo-bilibili-card本身，我直接运行 npm install 并 hexo clean 也会得到相同的结果。
 
 
进一步分析，似乎 jQuery 之类的依赖被打包成了一个 bundle.js 放到了最下面，但是这样和其他依赖的加载顺序是不一样的，因此还是会报错。
 
经过排查是依赖 hexo-filter-optimize 的问题。该插件会将 hexo 的各个资源（包括 js）进行打包来优化页面加载，但是影响了 jQuery 的加载顺序。（通过检查也可以发现，你提供的「安装前 blog」其实也没有安装 hexo-filter-optimize 因为，当使用 npm install 或安装 hexo-bilibili-card 时，他也会一并安装，导致了上诉问题。
 
以下是一些建议：
 
设置排除项（排除 jQuery 和 RemixIcon，保证引入顺序）
 # 在 _config.yml 追加: filter_optimize: enable: true # remove the surrounding comments in each of the bundled files remove_comments: false css:     # minify all css files     minify: true     # bundle loaded css files into one     bundle: true     # use a script block to load css elements dynamically     delivery: true     # make specific css content inline into the html page     #   - only support the full path     #   - default is ['css/main.css']     inlines:     excludes:     - ['/css/fonts/remixicon.css'] js:     # minify all js files     minify: true     # bundle loaded js files into one     bundle: true     excludes:     - ['/js/jquery-3.6.0.min.js']
 
或修改主题的 js 引入方式，使用 CDN 引入 jQuery 和 RemixIcon。

**Comment by maxchang3** [comment]
和主题关系不是很大。只是因为你安装了 `hexo-filter-optimize` 但是一开始没装好，安装 `hexo-bilibili-card` 的时候一起装上了，这个才是导致你问题的插件。他导致 jQuery 被捆绑成一个文件，运行在依赖于其的脚本之后。 根据我提供的信息配置下插件的忽略项或删除该插件即可。

无法交互是这个插件导致的结果，只是一开始定位到主题问题上了。

**Comment by 2010HCY** [comment]
神医啊，我卸了hexo-filter-optimize后我下载hexo-bilibili-card一遍就成功，而且界面一起正常，我现在安装其他插件都能流畅的安装，无报错，运行博客也从以前的十几秒变成5秒内，当代的赛博神医






                       
原始邮件
                       
                     

发件人："Max Chang"< ***@***.*** &gt;;

发件时间：2024/7/30 20:34

收件人："maxchang3/hexo-bilibili-card"< ***@***.*** &gt;;

抄送人："2010HCY"< ***@***.*** &gt;;"State change"< ***@***.*** &gt;;

主题：Re: [maxchang3/hexo-bilibili-card] Help me 帮帮我 (Issue #11)




 
说的很清楚了，因为你安装了 hexo-filter-optimize 但是一开始没装好，安装 hexo-bilibili-card 的时候一起装上了，他导致 jQuery 被捆绑成一个文件，运行在依赖于其的脚本之后。 根据我提供的信息配置下插件的忽略项或删除该插件即可。
