### ISSUE TITLE
css 使用 hexo inject 来插入head

### ISSUE THREAD

**Issue by appotry** [MaxChang3/hexo-bilibili-card#4]
https://hexo.io/zh-cn/api/injector

hexo 新api 可以随时随地插入 css js 到指定区域

**Comment by maxchang3** [comment]
好的，感谢提醒~ 我明天修改一下~ 这里确实可以用 injector~  不过这个应该不算新 api 了 hh。

这个 repo 算是黑历史了，当时还算初学阶段，基本上是比着一些插件写的，所以很多地方也写的比较丑和臃肿，比如里面还调用了一下 `node-fetch` 和 `nunjucks` 现在来说有点没必要了。

一直想整体重构一下比如类似于 [github-readme-stats](https://github.com/anuraghazra/github-readme-stats) 一样做成 svg 的样子。因为这个 css 自适应写的也不太好……

**Comment by appotry** [comment]
感谢回复，期待着改进版本

**Comment by appotry** [comment]
插入到head_begin更好，因为其它的用户css可能会改变一些css参数值

**Comment by appotry** [comment]
赞，测试基本正常
