### ISSUE TITLE
视频封面无法获取

### ISSUE THREAD

**Issue by YukiLx** [MaxChang3/hexo-bilibili-card#7]
近期我尝试使用这个插件，但是我发现网页中的B站卡片的封面都是默认封面。简单分析了一下代码发现封面图片是imageProxy+v_cover的组合，我暂时不清楚v_cover是否正确获取到了封面图片，但是ImageProxy网址应该是失效了。请问这个问题会修复吗

**Comment by maxchang3** [comment]
抱歉，这个插件一段时间没有维护了。封面获取应该是没问题的，但是目前内置的图片代理确实不能用了。考虑到之前设计不够充分，稍候我会增加一个自定义图片代理的配置项，让用户可以手工配置需要的图片代理。

**Comment by maxchang3** [comment]
0.6.2 版本替换了默认地址，增加了配置图片代理的方式，但是默认地址大陆部分地区仍不稳定，因此建议自建，或者若有更稳定的地址可以推荐给我~具体详见新的 README。
