### ISSUE TITLE
hexo g后报错

### ISSUE THREAD

**Issue by grape777** [MaxChang3/hexo-bilibili-card#9]
![Snipaste_2023-09-09_16-08-18.png](https://f.pz.al/pzal/2023/09/09/dc664f8c99908.png)
查了一下好像是无法识别｛% %｝这个，请问有办法解决吗

**Comment by maxchang3** [comment]
node 版本太低了，没有 fetch，请使用 node 18+

**Comment by grape777** [comment]
原来如此！就是这个原因 非常感谢！

**Comment by grape777** [comment]
原来如此！就是这个原因 非常感谢！
